# Generated by Django 2.1.5 on 2019-01-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20190116_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
